"""initial

Revision ID: 08f4355b5881
Revises: 
Create Date: 2026-08-25 14:07:10.838216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08f4355b5881'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attack_attempts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('target_name', sa.String(length=64), nullable=False),
    sa.Column('objective_category', sa.String(length=64), nullable=False),
    sa.Column('strategy', sa.String(length=64), nullable=False),
    sa.Column('converter_used', sa.String(length=128), nullable=True),
    sa.Column('full_transcript', sa.JSON(), nullable=False),
    sa.Column('target_action_taken', sa.String(length=256), nullable=True),
    sa.Column('blue_team_verdict', sa.String(length=32), nullable=True),
    sa.Column('blue_team_reasoning', sa.Text(), nullable=True),
    sa.Column('rules_fired', sa.JSON(), nullable=True),
    sa.Column('judge_analysis', sa.Text(), nullable=True),
    sa.Column('scorer_confidence', sa.Float(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attack_attempts_created_at'), 'attack_attempts', ['created_at'], unique=False)
    op.create_index(op.f('ix_attack_attempts_objective_category'), 'attack_attempts', ['objective_category'], unique=False)
    op.create_index(op.f('ix_attack_attempts_session_id'), 'attack_attempts', ['session_id'], unique=False)
    op.create_index(op.f('ix_attack_attempts_success'), 'attack_attempts', ['success'], unique=False)
    op.create_index(op.f('ix_attack_attempts_target_name'), 'attack_attempts', ['target_name'], unique=False)
    op.create_table('defense_rounds',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('guard_rules_snapshot', sa.JSON(), nullable=True),
    sa.Column('judge_prompt_snapshot', sa.Text(), nullable=True),
    sa.Column('total_attempts', sa.Integer(), nullable=True),
    sa.Column('successful_attacks', sa.Integer(), nullable=True),
    sa.Column('blocked_attacks', sa.Integer(), nullable=True),
    sa.Column('escalated_attacks', sa.Integer(), nullable=True),
    sa.Column('success_rate', sa.Float(), nullable=True),
    sa.Column('block_rate', sa.Float(), nullable=True),
    sa.Column('category_breakdown', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('round_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('defense_rounds')
    op.drop_index(op.f('ix_attack_attempts_target_name'), table_name='attack_attempts')
    op.drop_index(op.f('ix_attack_attempts_success'), table_name='attack_attempts')
    op.drop_index(op.f('ix_attack_attempts_session_id'), table_name='attack_attempts')
    op.drop_index(op.f('ix_attack_attempts_objective_category'), table_name='attack_attempts')
    op.drop_index(op.f('ix_attack_attempts_created_at'), table_name='attack_attempts')
    op.drop_table('attack_attempts')
    # ### end Alembic commands ###
