"""add_escalated_attacks_to_defense_round

Revision ID: 2dafa7fb35c6
Revises: 08f4355b5881
Create Date: 2026-08-25 15:31:12.019272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2dafa7fb35c6'
down_revision: Union[str, Sequence[str], None] = '08f4355b5881'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
